// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkX5l8wRYFsJ5u-MtMzswlj5GV9gD5Ivg',
    appId: '1:911673191155:web:d056671814aed93f90a586',
    messagingSenderId: '911673191155',
    projectId: 'education-app-262de',
    authDomain: 'education-app-262de.firebaseapp.com',
    storageBucket: 'education-app-262de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBij63Dvx_tTPg1u1T_hrZ_v025P9Q1je4',
    appId: '1:911673191155:android:5d947bd522c0a2f190a586',
    messagingSenderId: '911673191155',
    projectId: 'education-app-262de',
    storageBucket: 'education-app-262de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBcdCMxWWFN7_bESZf-fQofk85FSa9pw',
    appId: '1:911673191155:ios:3139d3ca31566a3d90a586',
    messagingSenderId: '911673191155',
    projectId: 'education-app-262de',
    storageBucket: 'education-app-262de.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBcdCMxWWFN7_bESZf-fQofk85FSa9pw',
    appId: '1:911673191155:ios:c203ce354aa5850a90a586',
    messagingSenderId: '911673191155',
    projectId: 'education-app-262de',
    storageBucket: 'education-app-262de.appspot.com',
    iosBundleId: 'com.example.educationApp.RunnerTests',
  );
}
